name: iaito CI

env:
  R2V: 5.7.0

on:
  push:
    branches:
    - fix-windows

jobs:
  w64-meson:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true # 'recursive' 'true' or 'false'
        persist-credentials: false
    - name: Preparing msvc toolchain
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
#    - uses: actions/setup-python@v1
#      with:
#        python-version: 3.8.x
#    - name: Prepare Qt
#      working-directory: build
#      shell: cmd
#      run: |
#        curl -vLo qt-unified-windows-x86-online.exe http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
#        qt-unified-windows-x86-online.exe --verbose --script ..\ci\qt.qs
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: dependencies
      shell: cmd
      run: |
        pip install ninja meson wget
        choco install zip 
#    - name: install r2
#      shell: bash
#      run: |
#        python -m wget https://github.com/radareorg/radare2/releases/download/${{env.R2V}}/radare2-${{env.R2V}}-w64.zip -o r2.zip
#        unzip r2.zip
#        mv radare2-${{env.R2V}}-w64 radare2
#        pwd
    - name: w64-make
      shell: cmd
      run: |
        SET ARCH=x64
        set IAITO_DEPS=%CD%\iaito-deps
        set PATH=%CD%\iaito-deps\qt\bin;%CD%\r2_dist\bin;%PATH%
        pip install meson ninja wget
        call preconfigure.bat
        call configure.bat
        call make.bat
        dir /s
    - uses: actions/upload-artifact@v2
      with:
        name: iaito.exe
        path: iaito
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: build/${{ env.PACKAGE_NAME }}
